apiVersion: v1
kind: Service
metadata:
   name: tor-backend-svc
   namespace: tor
   labels:
      app: tor-backend
spec:
   type: ClusterIP
   ports:
   - name: backend-port
     port: 9000
     targetPort: 9000
   selector:
     app: tor-backend
