apiVersion: v1
kind: PersistentVolume
metadata:
   name: tor-backend-pv
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteOnce
   storageClassName: manual
   hostPath:
     path: /k8s/tor-backend-pv
