apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-backend-pvc
  namespace: tor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
